"""先检验机制，再依据结果展开深度与交互实验；不把折数充作研究轮数。"""
DATASETS = ("ct_rate", "amos_mm", "mr_rate_1k")

# 每项是可检验的机制假设。新研究统一使用验证集，历史结果不作新对照。
BREADTH = [
    ("reference", {}, "重新建立本轮验证协议下的共同参考；不计作创新方案"),
    ("no_lqd", {"lqd_mode": "off"}, "整条反事实 logit 的负监督可能抵消正标签视觉证据，移除该项检验"),
    ("visual_aux", {"image_weight": .25}, "视觉路径没有直接监督，加入同尺度 ASL 检验其是否受到文本主导影响"),
    ("rank_lqd", {"lqd_mode": "ranking"}, "只要求正确文本比错配文本得分更高，避免要求同一正图像变为负类"),
    ("detached_swap", {"lqd_mode": "detach_swapped_visual"}, "切断错配项经视觉残差的直接梯度，检验 LQD 梯度路径冲突；检索路径仍可传递梯度"),
    ("no_lqd_visual_aux", {"lqd_mode": "off", "image_weight": .25}, "检验关闭 LQD 与视觉监督是否互补；与两个单因素方案同时比较"),
    ("visual_warmup", {"visual_warmup": 5, "image_weight": .25}, "先学习视觉证据再联合融合，检验训练先后次序"),
    ("delayed_lqd", {"lqd_delay": 8}, "待检索形成后再施加查询判别，检验早期错误检索的监督噪声"),
    ("query_detach", {"detach_query": True}, "阻断文本检索对视觉查询的反向塑形，检验跨模态梯度干扰"),
    ("fusion_gradient_routing", {"fusion_detach_visual": True, "image_weight": 1., "lqd_mode": "off"}, "借鉴 DGL 的梯度路由核心：视觉用独立目标优化，融合读取其特征；不是完整 DGL 复现"),
    ("report_dropout", {"report_dropout": .3}, "随机缺失报告提高视觉证据的必要性，检验文本捷径依赖"),
    ("classification_bce", {"classification_loss": "bce"}, "检验非对称负标签抑制是否削弱位置参数的有效训练信号"),
    ("identity_start", {"zero_warp_init": True}, "由恒等采集坐标启动，检验初始随机变形是否妨碍联合优化"),
    ("position_warmup", {"position_warmup": 8}, "逐步引入位置表示，检验早期位置与内容信号的尺度竞争"),
    ("position_lr", {"position_lr_multiplier": 3.}, "单独增加位置学习速率，检验位置参数学习不足而非表达不足"),
    ("position_input_detach", {"detach_position_input": True}, "让位置关系适应视觉表征，检验双向梯度耦合是否使两者不稳定"),
    ("absolute_only", {"route": "absolute"}, "独立检验绝对注入在本轮训练协议中的作用"),
    ("relative_only", {"route": "relative"}, "独立检验相对注意力偏置在本轮训练协议中的作用"),
    ("relative_first", {"placement": "relative_first"}, "仅浅层关系建模使用偏置，避免高层语义关系被同一偏置重复约束"),
    ("relative_last", {"placement": "relative_last"}, "在已有内容上下文上注入相对关系，检验位置使用时机"),
    ("late_absolute", {"placement": "late_absolute"}, "把绝对位置推迟到末层，检验早期内容表征受到位置扰动的假设"),
    ("late_both", {"placement": "late_both"}, "在末层联合注入两条位置路径，检验完整位置模块的放置位置"),
    ("valid_neighbors", {"descriptor": "valid_neighbors"}, "排除最后有效图像与 padding 的伪转变，检验边界描述偏差"),
    ("smooth_context", {"descriptor": "smooth3"}, "先整合局部邻域再估计变化，检验单步视觉差分的噪声敏感性"),
    ("current_gap", {"descriptor": "current_gap"}, "移除双侧变化，检验复杂描述是否在小数据下过拟合"),
    ("magnitude_context", {"descriptor": "magnitude_only"}, "保留变化强度而去掉方向交互，检验强度是否足以支持关系建模"),
    ("direction_context", {"descriptor": "direction_only"}, "仅用有符号变化，检验幅度及乘积是否导致尺度失衡"),
    ("unit_direction", {"descriptor": "unit_direction"}, "把变化方向与强度尺度分离，检验特征范数干扰"),
    ("label_position", {"label_position": True}, "让标签图像权重直接读取坐标、变形和二次位置项，检验位置到证据的传递瓶颈"),
    ("no_hypergraph", {"bypass_graph": True}, "移除超图以检验标签关系传播是否覆盖位置敏感的局部证据"),
    ("block_training", {"block_training": True}, "混合不同块数与删除比例训练，检验训练与块删除分布失配"),
    ("anchored_control", {"position": "anchored"}, "保持两条 Fourier 路径但固定 contextual coordinate 为采集锚点，分离变形与注入的贡献"),
    ("original_pe", {"position": "original_pe"}, "在相同训练和验证协议下对照 Original PE"),
    ("no_pe", {"position": "no_pe"}, "去除全部位置输入，检验预测实际依赖位置关系的程度"),
]

# 深度候选按已完成父方案的验证表现自适应展开，每次只修改一个因素。
# 参数深度明确标为深度，不计为新的核心机制或多篇理论创新。
DEPTH = [
    ("position_warmup", [3, 5, 12], "检验位置注入渐进训练的有效时间窗口"),
    ("image_weight", [.1, .5, 1.], "检验视觉监督强度是否决定父方案的收益/代价"),
    ("lqd_mode", ["off", "ranking"], "检验父方案对反事实监督定义的依赖"),
    ("lqd_weight", [.003, .03], "检验查询判别约束的有效尺度"),
    ("descriptor", ["valid_neighbors", "smooth3", "no_interaction", "no_current"], "检验父方案与上下文描述可靠性的交互"),
    ("placement", ["relative_first", "relative_last", "late_absolute", "late_both"], "检验父方案与位置进入视觉上下文的时机是否互补"),
    ("route", ["absolute", "relative", "both"], "分解父方案中两条位置路径的必要性"),
    ("zero_warp_init", [True], "检验父方案是否依赖坐标初始化"),
    ("warp_alpha", [.5, 1., 2.], "检验父方案允许的上下文变形范围"),
    ("absolute_scale", [.25, .5], "检验父方案的绝对信号尺度"),
    ("relative_scale", [.25, .5, 2.], "检验父方案的相对信号尺度"),
    ("lr", [1e-4, 4e-4], "检验父方案对全局优化速率的敏感性"),
    ("position_lr_multiplier", [.3, 3., 10.], "检验位置参数与主体网络的优化时间尺度"),
    ("report_dropout", [.15, .3, .5], "检验父方案是否仍依赖报告捷径"),
    ("label_position", [True], "检验父方案学得的位置是否需要直接进入标签证据聚合"),
    ("bypass_graph", [True], "检验父方案与标签关系推理是否存在冲突"),
    ("coordinate_penalty", [.01, .1], "以弱变形正则检验位置漂移；不把采集锚点解释为物理真值"),
    ("lqd_decay", [True], "基线的记录显示后期加权 LQD 梯度相对增大，检验衰减辅助目标是否改善联合优化"),
    ("lqd_gradient_cap", [.1, .25], "按 ACPE 实际梯度限制 LQD 的相对占比，检验晚期辅助梯度主导的假设"),
]
