gpu_ids: [0, 1, 2]
num_workers: 6

batch_size:
  demo_gastro_mil_baseline: 3
  demo_gastro_proto_moe_former: 3
  demo_colo_mil_baseline: 3
  demo_colo_count_aware_debias_mil: 3

eval_batch_size:
  demo_gastro_mil_baseline: 3
  demo_gastro_proto_moe_former: 3
  demo_colo_mil_baseline: 3
  demo_colo_count_aware_debias_mil: 3

min_instances: 1

train_max_instances:
  demo_gastro_mil_baseline: 24
  demo_gastro_proto_moe_former: 20
  demo_colo_mil_baseline: 24
  demo_colo_count_aware_debias_mil: 20

val_max_instances:
  demo_gastro_mil_baseline: 24
  demo_gastro_proto_moe_former: 20
  demo_colo_mil_baseline: 24
  demo_colo_count_aware_debias_mil: 20

test_max_instances:
  demo_gastro_mil_baseline: 24
  demo_gastro_proto_moe_former: 20
  demo_colo_mil_baseline: 24
  demo_colo_count_aware_debias_mil: 20

train_max_batch_instances:
  demo_gastro_mil_baseline: 72
  demo_gastro_proto_moe_former: 60
  demo_colo_mil_baseline: 72
  demo_colo_count_aware_debias_mil: 60

eval_max_batch_instances:
  demo_gastro_mil_baseline: 72
  demo_gastro_proto_moe_former: 60
  demo_colo_mil_baseline: 72
  demo_colo_count_aware_debias_mil: 60

train_sampling_strategy: random
eval_sampling_strategy: uniform

random_instance_dropout:
  demo_gastro_mil_baseline: 0.05
  demo_gastro_proto_moe_former: 0.08
  demo_colo_mil_baseline: 0.03
  demo_colo_count_aware_debias_mil: 0.08
