paths:
  project_root: /home/Lim/Project4  # 项目根目录
  dataset_base_root: /home/Lim/Project4/datasets  # 数据集根目录
  dataset_root: /home/Lim/Project4/datasets/main_data
  valid_dicts_pdf_csv: /home/Lim/Project4/outputs/cache_combine_reports/valid_dicts_pdf.csv
  valid_dicts_report_csv: /home/Lim/Project4/datasets/valid_dicts_report.csv
  output_dir: /home/Lim/Project4/outputs  # 输出根目录
  process_cache_dir_name: cache_combine_reports  # 过程缓存目录名
  check_similarity_dir_name: check_similarity  # 相似度检查输出目录名
